### ISSUE TITLE
Wrong server install URL is generated

### ISSUE THREAD

**Issue by Kevinjil** [3timeslazy/vscodium-devpodcontainers#26]
The version in the download URL is missing the final release digits. The release version is `1.97.0.25037`, but the extension tries to download version `1.97.0.`.

Logs:
```
[Trace  - 20:18:07.341] Server install command stderr:
https://github.com/VSCodium/vscodium/releases/download/1.97.0./vscodium-reh-linux-x64-1.97.0..tar.gz:
2025-02-10 20:18:07 ERROR 404: Not Found.
```

**Comment by PureTryOut** [comment]
Ah, this explains it. Is there any workaround available?

@3timeslazy have you experienced this yet?

**Comment by maxtidev** [comment]
We can change the download URL template as a workaround.

1. Navigate to `~/.vscode-oss/extensions/3timeslazy.vscodium-devpodcontainers-0.0.17-universal/dist/extension.js`
2. Remove both occurences of `.{$release}` (including the dot at the front!) in line 5 (corresponding to [this line of code](https://github.com/3timeslazy/vscodium-devpodcontainers/blob/a961dc3a2513b5449995d04734f10320af599803/src/vscodium/server.ts#L43)
3. Restart VS Codium / extensions

The extension seems to work fine after this. Note that while we could simply strip the extension of this now-deprecated release tag, this would break backwards-compatibility with earlier VS Codium versions. Making the dot conditional on `release` not being an empty string would be a cleaner solution in my mind.

**Comment by studioph** [comment]
> We can change the download URL template as a workaround.
> 
>     1. Navigate to `~/.vscode-oss/extensions/3timeslazy.vscodium-devpodcontainers-0.0.17-universal/dist/extension.js`
> 
>     2. Remove both occurences of `.{$release}` (including the dot at the front!) in line 5 (corresponding to [this line of code](https://github.com/3timeslazy/vscodium-devpodcontainers/blob/a961dc3a2513b5449995d04734f10320af599803/src/vscodium/server.ts#L43)
> 
>     3. Restart VS Codium / extensions
> 
> 
> The extension seems to work fine after this. Note that while we could simply strip the extension of this now-deprecated release tag, this would break backwards-compatibility with earlier VS Codium versions. Making the dot conditional on `release` not being an empty string would be a cleaner solution in my mind.

I haven't tried this myself, but I'm not seeing how removing the final part of the release version will help - you still need those final digits to get a valid download URL. Taking the example above from the OP:

```
https://github.com/VSCodium/vscodium/releases/download/1.97.0/vscodium-reh-linux-x64-1.97.0.tar.gz
```

will still give you a 404.

I'm not familiar with vsc extensions but I will take a look this weekend and see if I can find a fix and maybe make a PR since I really enjoy this extension.

**Comment by 3timeslazy** [comment]
I've merged @studioph 's PR and it worked for me. Just update to 0.0.18. I'm closing the issue, but feel free to reopen if needed.

**Comment by jdaibello** [comment]
Hi guys, sorry to reopen this, but I'm struggling with a similar error:

![Image](https://github.com/user-attachments/assets/dfca5c06-4f7c-4921-8d0a-848509b6e21f)

I'm using Windsurf

Some files maybe help:

argv.json:
```json
// This configuration file allows you to pass permanent command line arguments to VS Code.
// Only a subset of arguments is currently supported to reduce the likelihood of breaking
// the installation.
//
// PLEASE DO NOT CHANGE WITHOUT UNDERSTANDING THE IMPACT
//
// NOTE: Changing this file requires a restart of VS Code.
{
	// Use software rendering instead of hardware accelerated rendering.
	// This can help in cases where you see rendering issues in VS Code.
	// "disable-hardware-acceleration": true,

	// Allows to disable crash reporting.
	// Should restart the app if the value is changed.
	"enable-crash-reporter": true,

	// Unique id used for correlating crash reports sent from this instance.
	// Do not edit this value.
	"crash-reporter-id": "a1188397-dffc-441f-ba17-5262341997ac",

	// Enable proposed APIs - required for vscodium-devpodcontainers
	"enable-proposed-api": [
		"3timeslazy.vscodium-devpodcontainers"
	]
}
```

devcontainer.json
```json
{
  "name": "Game Service Dev Container",
  "dockerComposeFile": ["docker-compose.yml"],
  "service": "game-service",
  "workspaceFolder": "/workspace",
  "remoteUser": "bun",
  "customizations": {
    "vscode": {
      "settings": {
        "terminal.integrated.defaultProfile.linux": "zsh",
        "editor.formatOnSave": true,
        "editor.tabSize": 2,
        "files.eol": "\n",
        "files.autoSave": "afterDelay",
        "files.autoSaveDelay": 1000,
        "editor.codeActionsOnSave": {
          "source.fixAll": "explicit"
        },
        "typescript.tsdk": "node_modules/typescript/lib"
      },
      "extensions": [
        "eamodio.gitlens",
        "streetsidesoftware.code-spell-checker",
        "vscode.typescript-language-features"
      ]
    }
  },
  "forwardPorts": [3010, 5433],
  "postCreateCommand": "bun install",
  "shutdownAction": "stopCompose"
}
```

docker-compose.yml:
```yml
services:
  game-service:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    user: bun
    volumes:
      - ..:/workspace:cached
      - /workspace/node_modules
      - ~/.bun:/home/bun/.bun
      - ~/.npm:/home/bun/.npm
      - ~/.cache:/home/bun/.cache
    environment:
      - NODE_ENV=development
      - HOME=/home/bun
    working_dir: /workspace
    command: /bin/sh -c "while sleep 1000; do :; done"
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward a port from a Codespace.)
    # ports:
    #   - 3010:3010
    networks:
      - game-service-network
    # Uncomment the next line to use Docker from inside the container.
    # This works by using the Docker CLI to bind-mount the Docker socket.
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker-host.sock

  postgres-db:
    image: postgres:17.2-alpine3.21
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-idmsdb_dev}
      POSTGRES_USER: ${POSTGRES_DB:-idms}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-P@ssw0rd@dev}
      PGDATA: /var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - '5433:5432'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${POSTGRES_USER:-idms} -d ${POSTGRES_DB:-idmsdb_dev} -p 5432',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - game-service-network

networks:
  game-service-network:
    driver: bridge

volumes:
  postgres_data:
```

Dockerfile
```Dockerfile
# use the official Bun image
# see all versions at https://hub.docker.com/r/oven/bun/tags
FROM oven/bun:1.2.5

# Install system dependencies
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends \
    git \
    curl \
    wget \
    zsh \
    fonts-powerline \
    procps \
    lsb-release \
    ca-certificates \
    sudo \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set up the bun user (default user in oven/bun)
USER bun
WORKDIR /home/bun

# Install Oh My Zsh
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

# Install ZSH plugins
RUN git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k \
    && git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-autosuggestions \
    && git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting \
    && git clone https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-completions

# Copy custom .zshrc
COPY --chown=bun:bun .devcontainer/zshrc /home/bun/.zshrc

# Set the default shell to zsh
ENV SHELL /bin/zsh

# Set the working directory
WORKDIR /workspace

# Copy application files
COPY --chown=$USERNAME:$USERNAME . .

# Install Bun dependencies
RUN bun install

# Default command
CMD ["/bin/zsh"]
```

> $ code --version # VSCode                                                                                                                                     on git:develop|…1
0.50.7
02270c8441bdc4b2fdbc30e6f470a589ec78d600
x64

> $ codium --version  # VSCodium                                                                                                                                on git:develop|…1
zsh: command not found: codium

> $ windsurf --version # Windsurf                                                                                                                               on git:develop|…1
1.99.1
8cb7f313303c8b35844a56b6fe0f76e508261569
x64
